name: 使用Docker打包编译Go项目

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  Go-build:
    name: Go-Build工作 
    runs-on: ubuntu-latest
    steps:
    - name: 读取仓库内容
      uses: actions/checkout@v4

    - name: 设置Go版本
      uses: actions/setup-go@v3
      with:
        go-version: 1.22
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build the Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/template:latest
      

    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
